version : '3'
services :


  DB1 :
    image : mysql
    restart : always
    environment :
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - 3306:3306
    
  6th_container :
  #カレントディレクトリ中にあるDockerfileを参照してビルドする
    build : ./mysite_5
    ports :                 # 公開ポート
      - 8080:80             # 外部公開ポート番号：コンテナのポート番号
    volumes : 
      - .:/app_dir
    environment :
      6TH_CONTAINER_DB_PASSWORD :  aaaaa 
      #コンテナ起動の指定はDB1を優先。ただし、立ち上がら位までは待ってくれるとは限らない。 
    depends_on :
      - DB1
    links:
      - DB1:DB1
    tty: true
