version : '3'
services :


  DB1 :
    image : mysql:5.6
    restart : always
    environment :
      MYSQL_DATABASE: DB1
      MYSQL_ROOT_PASSWORD: qwerty
    expose:
      - '3306'
    
  7th_container :
  
  #カレントディレクトリ中にあるDockerfileを参照してビルドする
    build : ./mysite_5
    ports :                 # 公開ポート
      - 8000:8000             # 外部公開ポート番号：コンテナのポート番号（存在していないと接続できない）
    command : >
      bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000 && bash"
    volumes : 
      - .:/app_dir
    environment :
      6TH_CONTAINER_DB_PASSWORD :  aaaaa 
      #コンテナ起動の指定はDB1を優先。ただし、立ち上がら位までは待ってくれるとは限らない。 
    depends_on :
      - DB1
    links:
      - DB1:DB1
    tty: true